Document: pg-ft-czech
Title: Debian pg-ft-czech Manual
Author: <insert document author here>
Abstract: This manual describes what pg-ft-czech is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pg-ft-czech/pg-ft-czech.sgml.gz

Format: postscript
Files: /usr/share/doc/pg-ft-czech/pg-ft-czech.ps.gz

Format: text
Files: /usr/share/doc/pg-ft-czech/pg-ft-czech.text.gz

Format: HTML
Index: /usr/share/doc/pg-ft-czech/html/index.html
Files: /usr/share/doc/pg-ft-czech/html/*.html

  
